// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erqmyolcuzhirxpaavdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycW15b2xjdXpoaXJ4cGFhdmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2ODE0NzgsImV4cCI6MjA1ODI1NzQ3OH0.X-um0sP4TVi1hIzYiZvLX1t5MZSBpBlyIvB3LnzQM_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);